server:
  port: 8081
  servlet:
    context-path: /

websocket:
  server:
    ip: 127.0.0.1
    port: 8081

# 配置数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.23.121:3306/iam?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/**/*Mapper.xml
  type-aliases-package: com.beyondsoft.box.*.mapper

logging:
  level:
    com.beyondsoft.box: debug